//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ladder
    {
        public int Position { get; set; }
        public string LeagueName { get; set; }
        public string TeamName { get; set; }
        public int Played { get; set; }
        public int Points { get; set; }
        public int Wins { get; set; }
        public int Lost { get; set; }
        public int Byes { get; set; }
        public int For { get; set; }
        public int Against { get; set; }
        public int Diff_ { get; set; }
    
        public virtual League League { get; set; }
        public virtual Team Team { get; set; }
    }
}
