//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public string TeamName { get; set; }
        public string Position { get; set; }
        public int Age { get; set; }
        public string Biography { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
