//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRLFrontEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int RecordId { get; set; }
        public Nullable<int> Premierships { get; set; }
        public Nullable<int> RunnerUp { get; set; }
        public Nullable<int> MinorPremierships { get; set; }
        public Nullable<int> TotalWins { get; set; }
        public Nullable<int> TotalLosses { get; set; }
        public Nullable<double> WinPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
